config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'homes#top', as: 'root'
  get '/about', to: 'homes#about'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get :search
    end
  end
  resources :rooms, only: [:show] do
    member do
      get :join
    end
  end
  resources :posts do
    resource :like, only: [:create, :destroy]
    resources :rooms, only: [:create]
    resource :order, only: [:new]
  end
  
  resources :messages, only: [:create, :destroy]
  resources :orders, only: [:create] do
    member do
      get :finish
      get :confirm
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts
  with_options presence: true do
    validates :name, length: { minimum: 1, maximum: 50 }
    validates :image_id
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  with_options presence: true do
    validates :content, length: { minimum: 1, maximum: 500 }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :post
end

app/models/pay_post.rb
class PayPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_one :pay_post, dependent: :destroy
  has_one :room, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  accepts_nested_attributes_for :pay_post, allow_destroy: true

  enum is_deleted: { exit: false, not_exit: true }

  with_options presence: true do
    validates :title, length: { minimum: 1, maximum: 50 }
    validates :body, length: { minimum: 1, maximum: 3000 }
    validates :meeting_at
    validates :limit
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :post
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many   :tag_relationships, dependent: :destroy
  has_many   :users, through: :tag_relationships
  validates :name, uniqueness: true, length: { minimum: 1, maximum: 50 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = self.email.downcase}
  has_secure_password validations: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  with_options presence: true do
    validates :email, uniqueness: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :nickname, length: { maximum: 50 }
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :introduction, length: { maximum: 800 }
  end

  has_many :posts
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  accepts_nested_attributes_for :tag_relationships, allow_destroy: true


  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_root, only: [:show, :index, :search, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @not_image = "no_image.jpg"
    @tags = @user.tags

    @rooms = @user.rooms
    @like_posts = current_user.liked_posts
    @before_posts =[]
    @after_posts = []
    @rooms.each do |room|
      @before_posts << room.post if room.post.meeting_at > Time.current
      @after_posts << room.post if room.post.meeting_at <= Time.current
    end
  end

  def new
    @user = User.new
    @user.tag_relationships.build
  end

  def create
    @user = User.new(user_params)
    @user.deleted = false
    if @user.save

      if params[:user][:icon_image]
         File.binwrite("public/user_images/#{@user.id}.jpg", params[:user][:icon_image].read)
         @user.update(icon_image_id: "#{@user.id}.jpg" )
      else
         @user.update(icon_image_id: "no_image.jpg" )
      end

      log_in(@user)
      flash[:success] = "登録が完了しました！"
      redirect_to user_path(@user)
    else
      render new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)

      if params[:user][:icon_image]
         File.binwrite("public/user_images/#{@user.id}.jpg", params[:user][:icon_image].read)
         @user.update(icon_image_id: "#{@user.id}.jpg" )
      end

      flash[:success] = "保存が完了しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "保存が失敗しました。"
      render 'edit'
    end
  end

  def search
    @tags = Tag.all
    @tag = Tag.find_by(name: params[:tag_name])
    @users = @tag.users
  end

  def index
    @tags = Tag.all
    @user_tags = current_user.tags
    @users = []
    @tags.each do |tag|
      tag.users.each do |user|
        @users << user if user != current_user
      end
    end
    @users.uniq!
  end

  def destroy
  end

  private
  def redirect_root
    unless logged_in?
      flash[:success] = "ログインまたは、新規登録を行なってください。"
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :remember_token,
      :deleted,
      :introduction,
      :icon_image_id,
      { :tag_ids=> [] }
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      if @current_user.nil?
        @current_user = User.find_by(id: session[:user_id])
        return @current_user
      else
        return @current_user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<div class="xy_center">

  <%= render "shared/error_messages", user: @user %>

  <p class ="title">ユーザー編集</p>

  <%= form_with model: @user, local: true do |f| %>

    <div class="field">
      <%= f.label :アイコン %><br/>
      <%= f.file_field :icon_image %>
    </div>

    <div class="field">
      <%= f.label :ニックネーム %><br />
      <%= f.text_field :nickname, autofocus: true, style:"width: 300px;" %>
    </div>

    <div class="field">
      <%= f.label :紹介文%><br />
      <%= f.text_area :introduction, autofocus: true %>
    </div>

    <div class="">
      <%= f.submit "保存", class:"btn_green" %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="search">
  <div class="tags_box">
      <p class"tag_name_search">タグ名で検索</p>
      <div class="tag_center">
        <div class="tag_flex">
          <% @tags.each do |tag| %>
          <p class ="tag_link">
            <%= link_to search_users_path(tag_name: tag.name) do %>
              <%= tag.name %>
            <% end %>
          </p>
        <% end %>
        </div>
      </div>
    </div>

    <div class="recommendation_users">
      <p class="users_title">あなたに似ているユーザー</p>
      <div class="users">
        <div class="user_flex">
        <% @users.each do |user| %>
            <div class="user_card">
              <%= link_to user_path(user) do %>
                <div class="circle_img text-center ">
                  <% if !current_user.icon_image_id.blank? %>
                    <%= image_tag ("/user_images/#{user.icon_image_id}") %>
                  <% else %>
                    <%= image_tag ("/user_images/no_image.jpg") %>
                  <% end %>
                </div>
                <!--名前-->
                <p class="xy_center">
                  <%= user.nickname %>さん
                </p>
              <% end %>
              <div class="tag_flex_s">
                <% user.tags.each do |tag| %>
                <p class ="tag_link_s">
                  <%= link_to users_path(tag_name: tag.name) do %>
                    <%= tag.name %>
                  <% end %>
                </p>
              <% end %>
              </div>
            </div>
        <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<%= render "shared/error_messages", user: @user %>

<div class="xy_center">
  <p class="title">新規登録</p>

  <%= form_with model: @user, local: true do |f| %>

    <div class="field">
      <%= f.label :アイコン画像 %><br/>
      <%= f.file_field :icon_image %>
    </div>

    <div class="field">
      <%= f.label :ニックネーム %><br />
      <%= f.text_field :nickname, autofocus: true, style:"width: 300px;" %>
    </div>

    <div class="field">
      <%= f.label :紹介文%><br />
      <%= f.text_area :introduction, autofocus: true %>
    </div>
    
    <div class="tags">
      <div class="tag-group">
        <%= f.label :タグ, class: 'col-form-label' %>
      </div>
      <div class="tag-group tag-select-comment">
        <p>※関連するタグを選択してください（複数選択可）</p>
      </div>
      <div class="tag-group">
        <%= collection_check_boxes(:user, :tag_ids, Tag.all, :id, :name ) do |t|  %>
          <% t.label { t.check_box + t.text } %>
        <% end %>
      </div>
    </div>



    <div class="field">
      <%= f.label :メールアドレス %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" , style:"width: 300px;" %>
    </div>

    <div class="field">
      <%= f.label :パスワード %><br />
      <%= f.password_field :password, autocomplete: "new-password", style:"width: 300px;" %>
    </div>

    <div class="field">
      <%= f.label :パスワード確認 %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", style:"width: 300px;" %>
    </div>

    <%= f.hidden_field :deleted, value: false %>

    <div class="">
      <%= f.submit "新規登録" , class:"btn_blue mt_30px" %>
    </div>

  <% end %>
</div>

app/views/users/search.html.erb
<div class="search">

  <div class="tags_box">
    <p class"tag_name_search">タグ名で検索</p>
    <div class="tag_center">
      <div class="tag_flex">
        <% @tags.each do |tag| %>
        <p class ="tag_link">
          <%= link_to search_users_path(tag_name: tag.name) do %>
            <%= tag.name %>
          <% end %>
        </p>
      <% end %>
      </div>
    </div>
  </div>

  <div class="recommendation_users">
    <p class="users_title"><%= @tag.name %>をタグ付けしているユーザー</p>
    <div class="users">
      <div class="user_flex">
      <% @users.each do |user| %>
          <div class="user_card">
            <%= link_to user_path(user) do %>
              <div class="circle_img text-center ">
                <% if !current_user.icon_image_id.blank? %>
                  <%= image_tag ("/user_images/#{user.icon_image_id}") %>
                <% else %>
                  <%= image_tag ("/user_images/no_image.jpg") %>
                <% end %>
              </div>
              <!--名前-->
              <p class="xy_center">
                <%= user.nickname %>さん
              </p>
            <% end %>
            <div class="tag_flex_s">
              <% user.tags.each do |tag| %>
              <p class ="tag_link_s">
                <%= link_to users_path(tag_name: tag.name) do %>
                  <%= tag.name %>
                <% end %>
              </p>
            <% end %>
            </div>
          </div>
      <% end %>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="box_margin xy_center">
  <div class="text_right edit_btn">
    <%= link_to "変更する", edit_user_path(@user) , class: "border_btn" if current_user.id.to_s == params[:id] %>
  </div>
  <% unless @user == current_user %>
    <div class="text_right follow_link">
      <% if current_user.following?(@user) %>
        <%= link_to "フォロー中", user_relationships_path(@user.id), class: "border_btn follow_link", method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(@user.id), class: "border_btn follow_link" , method: :post %>
      <% end %>
    </div>
  <% end %>
  <!--アイコン画像-->
  <div class="circle_img text-center ">
    <% if !current_user.icon_image_id.blank? %>
      <%= image_tag ("/user_images/#{@user.icon_image_id}") %>
    <% else %>
       <%= image_tag ("/user_images/no_image.jpg") %>
    <% end %>
  </div>

  <!--名前-->
  <p class="xy_center">
    <%=  @user.nickname %>さん
  </p>
  <div class="follow_box">
    <div class="row btn pb_30px">
      <%= link_to user_followings_path(@user) do %>
        <p class="follow_p"><%= @user.followings.count %>フォロー中</p>
      <% end %>
      <%= link_to user_followers_path(@user)do %>
        <p class="follow_p"><%= @user.followers.count %>フォロワー</p>
      <% end %>
    </div>
  </div>

  <div class="tags_box">
    <% @tags.each do |tag| %>
    <p class ="tag">
      <%= tag.name %>
    </p>
    <% end %>
  </div>

  <div class="box border_bottom border_top text_left">
    <p>【自己紹介】</p>
    <%= @user.introduction %>
  </div>

  <% if params[:id] == current_user.id.to_s %>

    <div class="tab-list list-unstyled row">
      <p class="tab tab-active">
        これからの約束
      </p>
      <p class="tab">
        進行中・過去の約束
      </p>
      <p class="tab">
        いいねした約束
      </p>
    </div>


    <div class="tabbox-contents">
      <div class="tabbox box-show">
        <div class="posts_box xy_center">
          <ul class="cards7">
            <%= render partial: 'posts/posts', collection: @before_posts, as: :post %>
          </ul>
        </div>
      </div>
      <div class="tabbox">
        <div class="posts_box xy_center">
          <ul class="cards7">
            <%= render partial: 'posts/posts', collection: @after_posts, as: :post %>
          </ul>
        </div>
      </div>
      <div class="tabbox">
        <div class="posts_box xy_center">
          <ul class="cards7">
            <%= render partial: 'posts/posts', collection: @like_posts, as: :post %>
          </ul>
        </div>
      </div>

    </div>

  <% else %>
    <p class="user_post_title"><span class="user_name">「<%= @user.nickname %>さん」</span>の投稿した「yakusoku」</p>
    <div class="tab-list list-unstyled row">
      <p class="tab tab-active">
        これからの約束
      </p>
      <p class="tab">
        進行中・過去の約束
      </p>
    </div>

    <div class="tabbox-contents">
      <div class="tabbox box-show">
        <div class="posts_box xy_center">
          <ul class="cards7">
            <%= render partial: 'posts/posts', collection: @before_posts, as: :post %>
          </ul>
        </div>
      </div>
      <div class="tabbox">
        <div class="posts_box xy_center">
          <ul class="cards7">
            <%= render partial: 'posts/posts', collection: @after_posts, as: :post %>
          </ul>
        </div>
      </div>
  <% end %>

</div>