config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'homes#top', as: 'root'
  get '/about', to: 'homes#about'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get :search
    end
  end
  resources :rooms, only: [:show] do
    member do
      get :join
    end
  end
  resources :posts do
    resource :like, only: [:create, :destroy]
    resources :rooms, only: [:create]
    resource :order, only: [:new]
  end
  
  resources :messages, only: [:create, :destroy]
  resources :orders, only: [:create] do
    member do
      get :finish
      get :confirm
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts
  with_options presence: true do
    validates :name, length: { minimum: 1, maximum: 50 }
    validates :image_id
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  with_options presence: true do
    validates :content, length: { minimum: 1, maximum: 500 }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :post
end

app/models/pay_post.rb
class PayPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_one :pay_post, dependent: :destroy
  has_one :room, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  accepts_nested_attributes_for :pay_post, allow_destroy: true

  enum is_deleted: { exit: false, not_exit: true }

  with_options presence: true do
    validates :title, length: { minimum: 1, maximum: 50 }
    validates :body, length: { minimum: 1, maximum: 3000 }
    validates :meeting_at
    validates :limit
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :post
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many   :tag_relationships, dependent: :destroy
  has_many   :users, through: :tag_relationships
  validates :name, uniqueness: true, length: { minimum: 1, maximum: 50 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = self.email.downcase}
  has_secure_password validations: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  with_options presence: true do
    validates :email, uniqueness: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :nickname, length: { maximum: 50 }
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :introduction, length: { maximum: 800 }
  end

  has_many :posts
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  accepts_nested_attributes_for :tag_relationships, allow_destroy: true


  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :redirect_root, except: :index

  def index
    @posts = Post.where('meeting_at >= ?', Time.now).order(meeting_at: :asc)
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user

    @room = Room.new
    @room.users << current_user
    @meeting_at = @post.meeting_at
  end

  def new
    @post = Post.new
    @post.build_pay_post
    @room = Room.new
    @room.users << current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.meeting_at < Time.current
      flash[:danger] = "約束のお時間は、現時刻以降を、選択してください。"
      redirect_back(fallback_location: root_path)
    else
      if @post.save
        flash.now[:success] = "約束の投稿が完了しました。"
        redirect_to post_path(@post.id)
      else
         flash[:danger] = "約束の投稿を、失敗しました。"
         render"new"
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = "編集が完了しました。"
      redirect_to post_path(@post.id)
    else
      flash[:danger] = "保存が失敗しました。"
      render"new"
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:success] = "削除が完了しました。"
      redirect_to posts_path
    else
       flash[:danger] = "削除できませんした。"
      render :edit
    end

  end

  private

  def redirect_root
    unless logged_in?
      flash[:success] = "ログインまたは、新規登録を行なってください。"
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :meeting_at,
      :limit,
      :genre_id,
      :user_id,
      pay_post_attributes: [:id, :price, :_destroy]
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      if @current_user.nil?
        @current_user = User.find_by(id: session[:user_id])
        return @current_user
      else
        return @current_user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/posts/_posts.html.erb
<div class="card_box">

  <li class="card7">
    <div class="card-title">

      <div class="card__image-holder">
        <div class="card_image">
          <%= image_tag ("/genre_images/#{post.genre.image_id}") %>
        </div>
      </div>

      <a href="#" class="toggle-info btn7">
        <span class="left"></span>
        <span class="right"></span>
      </a>
      <p class="card_timecategory">
        <time class="pubdate entry-time dfont" itemprop="datePublished">
          <%= post.meeting_at.strftime("%Y-%m-%d") %>
        </time>
          <p>
            <%= post.meeting_at.strftime("%H:%M") %>〜の約束
          </p>
      </p>
      <p class="card_htitle">
        <%= post.title %>
      </p>
    </div>
    <div class="card-flap flap1">
      <div class="card-description">
        <%= post.body %>
      </div>
    </div>
  </li>
  <div class="link_box">
    <%= link_to "約束の詳細" , post_path(post) , class:"btn7" %>
  </div>

app/views/posts/edit.html.erb
<div class="box_margin xy_center">
  <div class="title">約束をつくる</div>
  <div class="field_box">

    <%= form_with model: @post, local: true do |f| %>

      <div class="field">
        <%= f.label :【タイトル】 %><br/>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :【説明】 %><br />
        <%= f.text_area :body, autofocus: true, style:"width: 300px;" %>
      </div>

      <div class="field">
        <%= f.label :【約束の時間】%><br />
        <%= f.datetime_field :meeting_at, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :【制限人数】%><br />
        <%= f.select :limit, options_for_select((1..20).to_a), {:prompt => true}, {:class => "form-control"} %>
      </div>

      <div class="field">
        <%= f.label :【ジャンル】%><br />
        <%= f.collection_select :genre_id, Genre.all, :id, :name,{:prompt => true}, {:class => "form-control"} %>
      </div>

      <div class="mt_30px">
        <%= f.submit "保存", class:"btn_green" %>
      </div>

      <div class="mt_30px">
        <%=link_to "削除", post_path, class:"btn_danger", method: :delete , data: {confirm: "削除しますか？"}%>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts_box xy_center">
  <ul class="cards7">
    <%= render partial: 'posts', collection: @posts, as: :post %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="box_margin xy_center">
  <%= render 'layouts/error', model: @post %>
  <div class="title">約束をつくる</div>
  <div class="field_box">

    <%= form_with model: @post, local: true do |f| %>

      <div class="field">
        <%= f.label :【タイトル】 %><br/>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :【説明】 %><br />
        <%= f.text_area :body, autofocus: true, style:"width: 300px;" %>
      </div>

      <div class="field">
        <%= f.label :【約束の時間】%><br />
        <%= f.datetime_field :meeting_at, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :【制限人数】%><br />
        <%= f.select :limit, options_for_select((1..20).to_a), {:prompt => true}, {:class => "form-control"} %>
      </div>

      <div class="field">
        <%= f.label :【ジャンル】%><br />
        <%= f.collection_select :genre_id, Genre.all, :id, :name,{:prompt => true}, {:class => "form-control"} %>
      </div>

      <div class="et_pb_module">
        <a href="#fuu" class='secList'>有料で投稿する場合は、こちらをクリックし価格を入力してください。</a>
      </div>

      <%= f.fields_for :pay_post do |ff| %>
        <div class="field section">
          <%= ff.label :price %><br>
          <%= ff.text_field :price %>円
        </div>
      <% end %>

      <div class="mt_30px">
        <%= f.submit "保存", class:"btn_green" %>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post_show">
  <div class="box">
    <div class="bg-image">
      <div class="genre_image">
        <%= image_tag asset_path("#{@post.genre.image_id}") %>
      </div>
      <p class="title_text"><%= @post.title %></p>
        <% if @post.room.present? %>
          <p class="title_text_s">
            <%= @post.room.users.count.to_s %> / <%= @post.limit.to_s %> 人
          </p>
        <% else %>
          <p class="title_text_s">
            0 / <%= @post.limit.to_s %> 人
          </p>
        <% end %>
      <% if @post.pay_post.price.present? %>
        <p class="pay_post">有料</p>
      <% end %>
      <% if @post.user == current_user %>
        <%= link_to "編集する", edit_post_path(@post), class:"border_btn post_edit_btn" %>
      <% end %>

     <div class="post_like_btn border_btn">
        <div id="likes_buttons_<%= @post.id %>">
          <%= render 'likes/like', post: @post %>
        </div>
      </div>
    </div>

    <div class="flex">
      <div class="left_box flow_item right_border">
        <p>お約束の時間</p>
        <p><%= @meeting_at.strftime("%Y年%m月%d日") %></p>
        <p class="time_lg"><%= @meeting_at.strftime("%H:%M") %>〜</p>
      </div>
      <div class="right_box flow_item flex">
        <div class="left_box flow_item user_box">
          <%= link_to user_path(@post.user) do %>
            <p>主催者：<%= @post.user.nickname %>さん</p>
            <div class="circle_img_s text-center ">
              <%= image_tag("/user_images/#{@post.user.icon_image_id}") %>
            </div>
          <% end %>
        </div>
        <div class="right_box flow_item">
          <p>参加者：</p>
          <div class="users_box_flex">
            <% if @post.room.blank? %>
              <p>参加者は、いません。</p>
            <% else %>
              <% @post.room.users.each do |user| %>
                <div class="users_box">
                  <p><%= user.nickname %>さん</p>
                  <div class="circle_img_ss text-center ">
                    <%= image_tag("/user_images/#{user.icon_image_id}") %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="post_show_btn">
      <% if @post.pay_post.price.blank? || @post.user == current_user %>
          <% if @post.user == current_user && @post.room.nil? %>
            <%= link_to "Roomを開く", post_rooms_path(@post), method: :post, class:"btn_green post_show_btn"%>
          <% elsif @post.user != current_user && @post.room.present? && @post.room.users.exclude?(current_user) %>
            <%= link_to "参加する", join_room_path(@post.room), class:"btn_blue"%>
          <% elsif @post.user != current_user && @post.room.nil? %>
            <p>ルームはまだ開かれていません。</p>
          <% else %>
            <%= link_to "Roomへ入る", room_path(@post.room), class:"btn_yellow"%>
          <% end %>
      <% else %>
        <% if @post.room.blank? %>
         <p>ルームはまだ開かれていません。</p>
        <% elsif @post.room.users.exclude?(current_user) %>
          <%= link_to "購入する", new_post_order_path(@post), class:"btn_yellow" %>
        <% else %>
          <%= link_to "Roomへ入る", room_path(@post.room), class:"btn_yellow"%>
        <% end %>
      <% end %>
    </div>

    <div class="body">
      <p class >【お約束の内容】</p>
      <p class="post_body">
        <%= @post.body %>
      </p>
    </div>
  </div>
</div>