config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'homes#top', as: 'root'
  get '/about', to: 'homes#about'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get :search
    end
  end
  resources :rooms, only: [:show] do
    member do
      get :join
    end
  end
  resources :posts do
    resource :like, only: [:create, :destroy]
    resources :rooms, only: [:create]
    resource :order, only: [:new]
  end
  
  resources :messages, only: [:create, :destroy]
  resources :orders, only: [:create] do
    member do
      get :finish
      get :confirm
    end
  end
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts
  with_options presence: true do
    validates :name, length: { minimum: 1, maximum: 50 }
    validates :image_id
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  with_options presence: true do
    validates :content, length: { minimum: 1, maximum: 500 }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :post
end

app/models/pay_post.rb
class PayPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_one :pay_post, dependent: :destroy
  has_one :room, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  accepts_nested_attributes_for :pay_post, allow_destroy: true

  enum is_deleted: { exit: false, not_exit: true }

  with_options presence: true do
    validates :title, length: { minimum: 1, maximum: 50 }
    validates :body, length: { minimum: 1, maximum: 3000 }
    validates :meeting_at
    validates :limit
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :post
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many   :tag_relationships, dependent: :destroy
  has_many   :users, through: :tag_relationships
  validates :name, uniqueness: true, length: { minimum: 1, maximum: 50 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = self.email.downcase}
  has_secure_password validations: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  with_options presence: true do
    validates :email, uniqueness: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :nickname, length: { maximum: 50 }
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :introduction, length: { maximum: 800 }
  end

  has_many :posts
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  accepts_nested_attributes_for :tag_relationships, allow_destroy: true


  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      if @current_user.nil?
        @current_user = User.find_by(id: session[:user_id])
        return @current_user
      else
        return @current_user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer-text">© All rights reserved by yakusoku.Inc.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <div>
    <%= link_to image_tag("yakusoku.png", width: 100), root_path, class:"navbar-brand" %>
  </div>
  <nav class="navbar">
    <div class = "nav-list">
      <% if logged_in? %>
        <div class="social">
          <%= link_to '予定を作る', new_post_path, class: 'blue' %>
        </div>

        <div class="social">
          <%= link_to '予定を探す', posts_path, class: 'blue' %>
        </div>

        <div class="social">
          <%= link_to 'ユーザー検索', users_path, class:'blue'%>
        </div>

        <div class="social">
          <%= link_to 'マイページ', user_path(current_user), class: 'blue' %>
        </div>

        <div class="social">
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'blue' %>
        </div>

      <% else %>

        <div class="social">
          <%= link_to 'About', root_path, class: 'blue' %>
        </div>


        <div class="social">
          <%= link_to '新規登録', new_user_path, class: 'blue' %>
        </div>

        <div class="social">
          <%= link_to 'ログイン', login_path, class: 'blue' %>
        </div>

      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <!--テスト用-->
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>